### ISSUE TITLE
Enrollment request

### ISSUE THREAD

**Issue by ethson** [CS193A/How-To#135]
First Name: Ethson
Last Name: Villegas
Stanford Email: ethson@stanford.edu

**Comment by dddutz** [comment]
Invited you! Go to https://github.com/CS193A to accept the invitation.

**Comment by ethson** [comment]
Hey Derin, I'm at huang right now but I can't find the OH, are you holding them today?
Sent using CloudMagic Email [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=7.9.8&pv=9.3&source=email_footer_2]
On Wed, Apr 6, 2016 at 1:17 PM, Derin Dutz <notifications@github.com> wrote:
Invited you! Go to https://github.com/CS193A [https://github.com/CS193A] to accept the invitation.

**Comment by dddutz** [comment]
Hi Ethson,

I'm on the first floor of Huang by the Forbes Family Cafe. Where are you?

Best,
Derin
