### ISSUE TITLE
Enrollment request

### ISSUE THREAD

**Issue by asrat19** [CS193A/How-To#165]
First Name: Asrat
Last Name: Alemu
Stanford Email: asrat19@stanford.edu

**Comment by dddutz** [comment]
Invited you! Go to https://github.com/CS193A to accept the invitation.

**Comment by asrat19** [comment]
Hi,

I'm guessing I submitted the first assignment in a wrong way because I just
saw all this emails today. I'm not sure how much it matters for the grade,
but to just let you know. And I know it's way too late to even try to
resubmit.

Best,

*Asrat *

**Comment by dddutz** [comment]
Hey Asrat,

Can you try submitting your assignment again or send it to me by email? If
you promise you finished it by the deadline and it was just a submission
problem, I can grade it for you.

Best,
Derin

**Comment by asrat19** [comment]
Hi Derin,

I resubmitted it. Let me know if you can find it.

And thanks a lot.

Best,
*Asrat G Alemu*
Stanford University | Class of 2019
