### ISSUE TITLE
Enrollment request

### ISSUE THREAD

**Issue by Shayne13** [CS193A/How-To#26]
## Enrollment request
**Full Name:** Shayne Longpre
**Stanford Email:** slongpre@stanford.edu

**Comment by dddutz** [comment]
It seems like you haven't accepted the CS193A organization invitation yet. Please go to https://github.com/CS193A

**Comment by dddutz** [comment]
In order to properly process your assignments and for you to take part in peer grading, you must join the CS193A organization. It seems like you haven't accepted the invitation yet. Please accept it by going to https://github.com/CS193A.

**Comment by dddutz** [comment]
Please join the organization. I've already invited you, so all you have to do is go to https://github.com/CS193A in order to join. It only takes a few seconds and it was technically a submission requirement for homework 1. I don't want to ding you, so please join.
