### ISSUE TITLE
Enrollment request

### ISSUE THREAD

**Issue by serrotnai** [CS193A/How-To#32]
## Enrollment request
**Full Name:** Ian Torres
**Stanford Email:** itorres@stanford.edu

**Comment by dddutz** [comment]
It seems like you haven't accepted the CS193A organization invitation yet. Please go to https://github.com/CS193A

**Comment by dddutz** [comment]
In order to properly process your assignments and for you to take part in peer grading, you must join the CS193A organization. It seems like you haven't accepted the invitation yet. Please accept it by going to https://github.com/CS193A.

**Comment by serrotnai** [comment]
Hi Derin,

Sorry, I missed your previous e-mail. I just clicked on the link; am I in
the organization now?

- Ian

**Comment by dddutz** [comment]
Yup!

Best,
Derin
