### ISSUE TITLE
Enrollment request

### ISSUE THREAD

**Issue by romeoumana** [CS193A/How-To#46]
## Enrollment request
**Full Name:** Romeo Umana
**Stanford Email:** romeou@stanford.edu

**Comment by dddutz** [comment]
It seems like you haven't accepted the CS193A organization invitation yet. Please go to https://github.com/CS193A

**Comment by dddutz** [comment]
In order to properly process your assignments and for you to take part in peer grading, you must join the CS193A organization. It seems like you haven't accepted the invitation yet. Please accept it by going to https://github.com/CS193A.
