### ISSUE TITLE
Enrollment request

### ISSUE THREAD

**Issue by jgarci10** [CS193A/How-To#72]
## Enrollment request
**Full Name:** Jorge Garcia
**Stanford Email:** jgarci10@stanford.edu

**Comment by dddutz** [comment]
It seems like you haven't accepted the CS193A organization invitation yet. Please go to https://github.com/CS193A

**Comment by jgarci10** [comment]
sorry about that.

___
Jorge Garcia
B.S. Symbolic Systems Candidate
Stanford University | Class of 2017
